server:
    port: 8081

spring:
  config:
    import: optional:file:.env
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ["openid", "profile", "email"]
            redirect-uri: ${GOOGLE_REDIRECT_URL}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate.format_sql: true
        hibernate.jdbc.time_zone: Asia/Seoul
    flyway:
      enabled: true
      locations: classpath:db/migration

notify:
  enabled: true
  slack:
    enabled: true
    webhook: ${SLACK_WEBHOOK_URL}
  discord:
    enabled: true
    webhook: ${DISCORD_WEBHOOK_URL}

url:
  script:
    marked: https://cdn.jsdelivr.net/npm/marked@12.0.2/marked.min.js
    safe-guard: https://cdn.jsdelivr.net/npm/dompurify@3.1.6/dist/purify.min.js
    jquery: /webjars/jquery/3.7.1/jquery.min.js
  base: https://inbok.shop
  jsp: /WEB-INF/views
  css: /css
  image: /image

auth:
  cookie:
    domain: inbok.shop
    secure: true # 로컬 http면 false
    same-site: Lax
    access-name: ACCESS
    refresh-name: REFRESH
    access-max-age-mins: 15
    refresh-max-age-days: 14

jwt:
  issuer: lifelog
  secret: ${JWT_SECRET}
  access-exp-minutes: 15
  refresh-exp-days: 14